load ALUProcess.hdl,
output-file ALUProcess.out,
compare-to ALUProcess.cmp,
output-list time%S1.4.1  a%D1.3.1 b%D1.3.1 out%D1.3.1 hiLo%B3.1.3 ands%B3.1.3 sums%B3.1.3 xors%B3.1.3 ors%B3.1.3 carryIn%B3.1.3 carryOut%B3.1.3 resLoad%B3.1.3; 


set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 3,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 4, set b 4,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 7,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 8,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 6, set b 3,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 4, set b 4,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 8, set b 7,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 8, set b 8,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 15, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 15, set b 0,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 10, set b 10,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 10, set b 10,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 9, set b 3,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 6, set b 12,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 6, set b 1,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 4, set b 11,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 8, set b 8,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 8, set b 7,
set hiLo 1,
set ands 0,
set sums 1,
set xors 0,
set ors 0,
set carryIn 1,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 3,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 4, set b 4,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 7,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 8,
set hiLo 1,
set ands 1,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 3,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 4, set b 4,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 7,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 8,
set hiLo 1,
set ands 0,
set sums 0,
set xors 0,
set ors 1,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 15, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 10, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 5,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 3,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 9, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 12,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 4, set b 4,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 6, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 14,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 7,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 15,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 8, set b 8,
set hiLo 1,
set ands 0,
set sums 0,
set xors 1,
set ors 0,
set carryIn 0,
set resLoad 1,
tick, tock, output;
set a 0, set b 0,
set hiLo 0,
set ands 0,
set sums 0,
set xors 0,
set ors 0,
set carryIn 0,
set resLoad 0,
tick, tock, output;
